[package]
name = "bernie"
version = "0.1.0"
edition = "2021"

[features]
default = ["database"]
database = ["sqlx"]

[dependencies]
tokio = { version = "~1.15", features = ["full"] }
chrono = "0.4.19"
dotenv = "0.15.0"
url = "2.2.2"
async-trait = "0.1.52"
anyhow = "1.0.53"

sqlx = { version = "0.5.10", features = ["runtime-tokio-rustls", "postgres", "chrono"], optional = true }

[dependencies.serenity]
version = "0.10"
default-features = false
features = [
    # default features
    "builder",
    "cache",
    "client",
    #    "framework",
    "gateway",
    "http",
    "model",
    #    "standard_framework",
    "utils",
    "rustls_backend",
    # extra features
    "voice",
]