version: '3'

services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  bernie:
    build: .
    volumes:
      - bernie:/var/lib/bernie
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      RUST_LOG: "error,bernie=debug"
    restart: unless-stopped
    depends_on:
      # - db
volumes:
  postgres:
  bernie:
